### ISSUE TITLE
Add a quick-swap for the clicker

### ISSUE THREAD

**Issue by evanbrobertson** [evanbrobertson/expense_app#41]
I frequently need to increment the clicker to more than +1, but the only way to do that is to open the settings, which is annyoing.

Add a switch that is like two arrows going up and down but back to back, like <> but vertical, right next to the clicker. Far enough so you don't tap it by accident though, edge of the screen.

These should swap between +1, +3, and +5.

In countries where the currency is stronger, less clicks, but in CAD, most things cost $5+ is seems, so to get a cart of $100 groceries took a LOT of clicks. But, it did work, so that's something.

**Comment by LostRhapsody** [comment]
Completed in bc0f98a591437a36f5fa2cfcdc253f3e393befe9
